---
title: "Untitled"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load

```{r load}
library(devtools)
library(tidyverse)
library(roxygen2)
library(ggthemr)
ggthemr("dust")
load_all()
```

```{r nLTT}
colless_result <- purrr::map(filtlist, function(x) {
  purrr::map(x, colless_batch)
})
colless_result <- colless_batch(filtunlist)

foo <- function(x, metric = "colless") {
  if (metric == "colless") {
    xx <- apTreeshape::as.treeshape(x) # convert to apTreeshape format
    apTreeshape::colless.test(xx, "yule") # calculate colless' metric
  } else
    if (metric == "gamma") {
      ape::gammaStat(x)
    } else
      stop("metric should be one of colless or gamma")
}

tesmulti<-filtunlist
class(tesmulti)<-"multiPhylo"
gamma_metric<-plyr::ldply(tesmulti, foo, metric = "gamma")
colless_metric<-plyr::ldply(trees, foo, metric = "colless")

gamma_table <- gamma_metric%>%mutate(Gamma = 2*(1 - pnorm(abs(V1))))
  extract(col = Pars, into = c("Lambda", "Mu","Beta_N","Beta_Phi","Gamma_N","Gamma_Phi"), "c\\((.+)\\,(.+)\\,(.+)\\,(.+)\\,(.+)\\,(.+)\\)")


outunlist <- unlist(out, recursive = FALSE)
filtlist <- outunlist %>% purrr::keep(grepl("tes", names(.)))
filtunlist<-unlist(filtlist, recursive = FALSE)
pd<-lapply(filtunlist, DDD::phylo2pd)
pd_table<-pd %>% 
  as_tibble %>%
  pivot_longer(
    everything(),
    names_to = c("Group", "Variable", "Replication"),
    values_to = "Value",
    names_pattern = "(\\d+)\\.(\\D+)(\\d+)"
  ) %>% 
  mutate(Variable = "pd_tes")

parslist <- outunlist %>% purrr::keep(grepl("all_pars", names(.)))
parsunlist<-unlist(parslist,recursive=FALSE)
parsage<-parsunlist%>% purrr::keep(grepl("all_pars.age", names(.)))
age_table <- parsage %>%
  as_tibble %>%
    pivot_longer(
    everything(),
    names_to = c("Group", "noneed"),
    values_to = "Age",
    names_pattern = "(\\d+)\\.(.+)"
  ) %>% select(-noneed)

parsmodel<-parsunlist%>% purrr::keep(grepl("all_pars.model", names(.)))
model_table <- parsmodel %>%
  as_tibble %>%
    pivot_longer(
    everything(),
    names_to = c("Group", "noneed"),
    values_to = "Model",
    names_pattern = "(\\d+)\\.(.+)"
  ) %>% select(-noneed)

parsmetric<-parsunlist%>% purrr::keep(grepl("all_pars.metric", names(.)))
metric_table <- parsmetric %>%
  as_tibble %>%
    pivot_longer(
    everything(),
    names_to = c("Group", "noneed"),
    values_to = "Metric",
    names_pattern = "(\\d+)\\.(.+)"
  ) %>% select(-noneed)

parsoffset<-parsunlist%>% purrr::keep(grepl("all_pars.offset", names(.)))
offset_table <- parsoffset %>%
  as_tibble %>%
    pivot_longer(
    everything(),
    names_to = c("Group", "noneed"),
    values_to = "offset",
    names_pattern = "(\\d+)\\.(.+)"
  ) %>% select(-noneed)

pars<-parsunlist%>% purrr::keep(grepl("all_pars.pars", names(.)))
pars_table <- pars %>%
  as_tibble %>%
    pivot_longer(
    everything(),
    names_to = c("Group", "noneed"),
    values_to = "Pars",
    names_pattern = "(\\d+)\\.(.+)"
  ) %>% 
  select(-noneed) %>%
  extract(col = Pars, into = c("Lambda", "Mu","Beta_N","Beta_Phi","Gamma_N","Gamma_Phi"), "c\\((.+)\\,(.+)\\,(.+)\\,(.+)\\,(.+)\\,(.+)\\)")


mpd<-lapply(filtunlist, DDD::phylo2mpd)


mpd_table<-mpd %>% 
  as_tibble %>%
  pivot_longer(
    everything(),
    names_to = c("Group", "Variable", "Replication"),
    values_to = "Value",
    names_pattern = "(\\d+)\\.(\\D+)(\\d+)"
  ) %>% 
  mutate(Variable = "mpd_tes")

jointed_table<-rbind(pd_table,mpd_table)
joined_table_all<-plyr::join_all(list(jointed_table,age_table,pars_table,model_table,metric_table,offset_table), by = "Group", type = "left")


joined_table_all2 <- joined_table_all %>% mutate(Combination = factor(str_replace(
    interaction(Beta_N,Beta_Phi,Gamma_N,Gamma_Phi), '\\.', ''
  )))
```
```{r pd g combo f mu ~ lambda, width = 8, height=8}
ggplot(filter(joined_table_all2, Variable == "pd_tes" & Age == 5)) +
  geom_boxplot(aes(Combination, Value, fill = Combination)) +
  viridis::scale_fill_viridis(discrete = TRUE, name = "Beta_N, Beta_Phi, Gamma_N, Gamma_Phi") +
  facet_grid(Mu ~ Lambda) +
  ggtitle("Grouped by combination, faceted by mu ~ lambda") +
  labs(y = "Phylogenetic diversity", x = "Beta_N, Beta_Phi, Gamma_N, Gamma_Phi") +
  theme(legend.title = element_text(size = 8),
        axis.text.x = element_text(size = 8, angle = -90),
        legend.position = "none")

ggsave(
  filename = "result/plot/pd_g_combo_f_muandlambda.png",
  device = "png",
  dpi = "retina",
  width = 8,
  height = 8
)

```
```{r mpd g combo f mu ~ lambda, width = 8, height=8}
ggplot(filter(joined_table_all2, Variable == "mpd_tes" & Age == 5)) +
  geom_boxplot(aes(Combination, Value, fill = Combination)) +
  viridis::scale_fill_viridis(discrete = TRUE, name = "Beta_N, Beta_Phi, Gamma_N, Gamma_Phi") +
  facet_grid(Mu ~ Lambda) +
  ggtitle("Grouped by combination, faceted by mu ~ lambda") +
  labs(y = "Mean pairwise distance", x = "Beta_N, Beta_Phi, Gamma_N, Gamma_Phi") +
  theme(legend.title = element_text(size = 8),
        axis.text.x = element_text(size = 8, angle = -90),
        legend.position = "none")

ggsave(
  filename = "result/plot/mpd_g_combo_f_muandlambda.png",
  device = "png",
  dpi = "retina",
  width = 8,
  height = 8
)

```


```{r pd g combo f mu, width = 12, height=4}
ggplot(filter(joined_table_all2, Variable == "pd_tes" & Age == 5)) +
  geom_boxplot(aes(Lambda, Value, fill = Combination)) +
  viridis::scale_fill_viridis(discrete = TRUE, name = "Beta_N, Beta_Phi, Gamma_N, Gamma_Phi") +
  facet_wrap(Mu ~ .) +
  ggtitle("Grouped by combination, faceted by mu") +
  labs(y = "Phylogenetic diversity") +
  theme(legend.title = element_text(size = 8))

ggsave(
  filename = "result/plot/pd_g_combo_f_mu.png",
  device = "png",
  dpi = "retina",
  width = 12,
  height = 4
)
```

```{r mpd g combo f mu, width = 12, height=4}
ggplot(filter(joined_table_all2, Variable == "mpd_tes"& Age == 5)) +
  geom_boxplot(aes(Lambda, Value, fill = Combination)) +
  viridis::scale_fill_viridis(discrete = TRUE, name = "Beta_N, Beta_Phi, Gamma_N, Gamma_Phi") +
  facet_wrap(Mu ~ .) +
  ggtitle("Grouped by combination, faceted by mu") +
  labs(y = "Mean pairwise distance") +
  theme(legend.title = element_text(size = 8))

ggsave(
  filename = "result/plot/mpd_g_combo_f_mu.png",
  device = "png",
  dpi = "retina",
  width = 12,
  height = 4
)

test_smaller <-
  edd_go(
    combo = combo,
    nrep = 3,
    name = "no_save",
    seed = 1,
    strategy = "sequential",
    workers = 8
  )
```

```{r pd g lambda f mu, width = 8, height=4}
ggplot(filter(joined_table_all2, Variable == "pd_tes" & Age == 5)) + geom_boxplot(aes(Combination, Value, fill = Lambda)) + viridis::scale_fill_viridis(discrete = TRUE) +
  facet_wrap(Mu ~ .) +
  theme(axis.text.x = element_text(size = 8, angle = -90)) +
  labs(x = "Beta_N, Beta_Phi, Gamma_N, Gamma_Phi", y = "Phylogenetic diversity") +     ggtitle("Grouped by lambda, faceted by mu")


ggsave(
  filename = "result/plot/pd_g_lambda_f_mu.png",
  device = "png",
  dpi = "retina",
  width = 12,
  height = 4
)
```
```{r mpd g lambda f mu, width = 8, height=4}
ggplot(filter(joined_table_all2, Variable == "mpd_tes" & Age == 5)) + geom_boxplot(aes(Combination, Value, fill = Lambda)) + viridis::scale_fill_viridis(discrete = TRUE) +
  facet_wrap(Mu ~ .) +
  theme(axis.text.x = element_text(size = 8, angle = -90)) +
  labs(x = "Beta_N, Beta_Phi, Gamma_N, Gamma_Phi", y = "Mean pairwise distance") +     ggtitle("Grouped by lambda, faceted by mu")

ggsave(
  filename = "result/plot/mpd_g_lambda_f_mu.png",
  device = "png",
  dpi = "retina",
  width = 12,
  height = 4
)
```
