// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// l_to_newick_ed_cpp
std::string l_to_newick_ed_cpp(const Rcpp::NumericMatrix& ltable_R, const double t, bool drop_extinct);
RcppExport SEXP _eve_l_to_newick_ed_cpp(SEXP ltable_RSEXP, SEXP tSEXP, SEXP drop_extinctSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type ltable_R(ltable_RSEXP);
    Rcpp::traits::input_parameter< const double >::type t(tSEXP);
    Rcpp::traits::input_parameter< bool >::type drop_extinct(drop_extinctSEXP);
    rcpp_result_gen = Rcpp::wrap(l_to_newick_ed_cpp(ltable_R, t, drop_extinct));
    return rcpp_result_gen;
END_RCPP
}
// calculate_CI
NumericMatrix calculate_CI(const List& brts_list, const NumericVector& tt, const float alpha);
RcppExport SEXP _eve_calculate_CI(SEXP brts_listSEXP, SEXP ttSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type brts_list(brts_listSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type tt(ttSEXP);
    Rcpp::traits::input_parameter< const float >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_CI(brts_list, tt, alpha));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_eve_l_to_newick_ed_cpp", (DL_FUNC) &_eve_l_to_newick_ed_cpp, 3},
    {"_eve_calculate_CI", (DL_FUNC) &_eve_calculate_CI, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_eve(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
