#' @name edd_stat
#' @title Generating plots for a replicated edd simulation
#' @description Function to automatically generate several plots from raw data
#' of a replicated edd simulation
#' @param raw_data a list of results generated by edd simulation function
#' @return a plot pack containing several plots
#' @author Tianjian Qin
#' @keywords phylogenetics
#' @export edd_stat
edd_stat <- function(raw_data = NULL){
  if (is.null(raw_data)) stop("No data provided")
  if (length(raw_data) != 10) stop("Bad raw data")
  correct_names <- c("all_pars", "tes", "tas", "l_tables", "brts", "nltt",
                     "eds", "las", "mus", "linlists")
  if (!identical(names(raw_data), correct_names)) {
    stop("Invalid raw data, did you forget to set history = TRUE?")
  }

  # plot lineages through time
  stat_balance <- edd_stat_balance(raw_data)

  # plot speciation rates
  stat_brts <- edd_stat_brts(raw_data) # histogram/model fitting

  # plot extinction rates
  stat_nltt <- edd_stat_nltt(raw_data)

  # plot evolutionary distinctiveness-es
  stat_gamma <- edd_stat_gamma(raw_data)

  stat_pack <- list(stat_balance = stat_balance,
                    stat_brts = stat_brts,
                    stat_nltt = stat_nltt,
                    stat_gamma  = stat_gamma
  )

  return(stat_pack)
}



stat_balance <- function(raw_data = NULL, method = "aldous") {

}
