#' @name edd_plot
#' @title Generating plots for a replicated edd simulation
#' @description Function to automatically generate several plots from raw data
#' of a replicated edd simulation
#' @param raw_data a list of results generated by edd simulation function
#' @param save_plot Logical, decides whether to save the plots to files
#' @return a plot pack containing several plots
#' @author Tianjian Qin
#' @keywords phylogenetics
#' @export edd_plot
edd_plot <- function(raw_data = NULL, save_plot = FALSE){
  if (is.null(raw_data)) stop("No data provided")
  if (length(raw_data) != 10) stop("Bad raw data")
  correct_names <- c("all_pars", "tes", "tas", "l_tables", "brts", "nltt",
                     "eds", "las", "mus", "linlists")
  if (!identical(names(raw_data), correct_names)) stop("Bad raw data")

  # plot lineages through time
  plot_nltt <- lapply(raw_data, edd_plot_nltt, save_plot = save_plot)

  # plot speciation rates
  plot_las <- edd_plot_las(raw_data)

  # plot extinction rates
  plot_mus <- edd_plot_mus(raw_data)

  # plot evolutionary distinctiveness-es
  plot_eds <- edd_plot_eds(raw_data)

  plot_pack <- list(plot_nltt = plot_nltt,
                    plot_las = plot_las,
                    plot_mus = plot_mus,
                    plot_eds = plot_eds
                    )

  return(plot_pack)
}

#' @name edd_plot_nltt
#' @title Generating nLTT plot for a replicated edd simulation
#' @description Function to generate normalized lineages through time plot from
#' raw data of a replicated edd simulation
#' @param raw_data a list of results generated by edd simulation function
#' @param drop_extinct Logical, decides whether to drop extinct lineages
#' @param save_plot Logical, decides whether to save the plots to files
#' @return an plot object
#' @author Tianjian Qin
#' @keywords phylogenetics
#' @export edd_plot_nltt
edd_plot_nltt <- function(raw_data = NULL,
                          drop_extinct = TRUE,
                          save_plot = FALSE
                          ) {
  if (drop_extinct == TRUE) {
    message("Drawing nLTT plot with trees of extant species")
    df <- nLTT::get_nltt_values(raw_data$tes, dt = 0.01)
  } else {
    message("Drawing nLTT plot with trees of all species")
    df <- nLTT::get_nltt_values(raw_data$tas, dt = 0.01)
  }

  lambda <- round(raw_data$all_pars$pars[[1]][1], digits = 3)
  mu <- round(raw_data$all_pars$pars[[1]][2], digits = 3)
  beta_n <- round(raw_data$all_pars$pars[[1]][3], digits = 3)
  beta_phi <- round(raw_data$all_pars$pars[[1]][4], digits = 3)
  gamma_n <- round(raw_data$all_pars$pars[[1]][5], digits = 3)
  gamma_phi <- round(raw_data$all_pars$pars[[1]][6], digits = 3)
  age <- raw_data$all_pars$age
  model <- levels(raw_data$all_pars$model)
  metric <- levels(raw_data$all_pars$metric)
  offset <- levels(raw_data$all_pars$offset)

  anno <- tibble(
    label = c(
      paste0(
        "<span style='color:#505050'>",
        "&lambda;<sub>0</sub> = ",
        lambda,
        "<br>",
        "&mu;<sub>0</sub> = ",
        mu,
        "<br>",
        "&beta;<sub>*N*</sub> = ",
        beta_n,
        "<br>",
        "&beta;<sub>*&Phi;*</sub> = ",
        beta_phi,
        "<br>",
        "&gamma;<sub>*N*</sub> = ",
        gamma_n,
        "<br>",
        "&gamma;<sub>*&Phi;*</sub> = ",
        gamma_n,
        "</span>"
      ),
      paste0(
        "<span style='color:#505050'>",
        "Age = ",
        age,
        "<br>",
        "Model = ",
        model,
        "<br>",
        "Metric = ",
        metric,
        "<br>",
        "Offset = ",
        offset,
        "</span>"
      )
    ),
    x = c(0, 0),
    y = c(0.33, .74),
    hjust = c(0, 0),
    vjust = c(0, 0),
    angle = c(0, 0)
  )

  plot_nltt <-
    ggplot2::ggplot() + ggplot2::geom_point(data = df,
                                            ggplot2::aes(t, nltt, color = id),
                          size = I(0.1)) +
    ggplot2::stat_summary(data = df,
                          ggplot2::aes(t, nltt),
                 fun.data = "mean_cl_boot",
                 geom = "smooth") +
    ggplot2::ggtitle("Average nLTT plot of phylogenies") +
    ggplot2::labs(x = "Normalized time", y = "Normalized number of lineages") +
    #scale_colour_ggthemr_d() +
    ggtext::geom_richtext(
      data = anno,
      ggplot2::aes(
        x,
        y,
        label = label,
        angle = angle,
        hjust = hjust,
        vjust = vjust
      ),
      fill = "#E8CB9C"
    ) +
    viridis::scale_colour_viridis(discrete = TRUE, option = "A") +
    ggplot2::xlim(0, 1) +
    ggplot2::ylim(0, 1) +
    ggplot2::theme(legend.position = "none",
          aspect.ratio = 3 / 4)

  if (save_plot == TRUE) {
    if (drop_extinct == TRUE) {
      ggplot2::ggsave(
        paste0(
          "result/plot/nltt/tes/",
          lambda,
          "_",
          mu,
          "_",
          beta_n,
          "_",
          beta_phi,
          "_",
          gamma_n,
          "_",
          gamma_phi,
          "_",
          age,
          "_",
          model,
          "_",
          metric,
          "_",
          offset,
          ".png"
        ),
        device = "png",
        dpi = "retina"
      )
    } else {
      ggplot2::ggsave(
        paste0(
          "result/plot/nltt/tas/",
          lambda,
          "_",
          mu,
          "_",
          beta_n,
          "_",
          beta_phi,
          "_",
          gamma_n,
          "_",
          gamma_phi,
          "_",
          age,
          "_",
          model,
          "_",
          metric,
          "_",
          offset,
          ".png"
        ),
        device = "png",
        dpi = "retina"
      )
    }
  }

  return(plot_nltt)
}



#' @name edd_plot_ltt
#' @title Generating LTT plot for a replicated edd simulation
#' @description Function to generate lineages through time plot from
#' raw data of a replicated edd simulation
#' @param raw_data a list of results generated by edd simulation function
#' @param alpha Resolution of the confidence interval
#' @param save_plot true or false, to decide whether to save the plots to files
#' @return an plot object
#' @author Tianjian Qin
#' @keywords phylogenetics
#' @export edd_plot_ltt
edd_plot_ltt <-
  function(raw_data = NULL,
           alpha = 0.05,
           save_plot = FALSE
           ) {
    pars_list <- extract_parameters(raw_data)

    brts <- lapply(raw_data$l_tables, function(x) {
      x[-1, 1]
    })

    ts <- unlist(brts)
    ts <- unique(ts)
    ts <- sort(ts)

    df <- calculate_CI(brts, ts, alpha = alpha)
    colnames(df) <- c("t", "median", "minalpha", "maxalpha", "mean")
    df <- as.data.frame(df)

    anno <- create_annotation(pars_list, vjust = c(1, 2.1))

    plot_ltt <-
      ggplot2::ggplot(df) + ggplot2::geom_line(ggplot2::aes(t, mean)) +
      ggplot2::geom_ribbon(ggplot2::aes(t, mean, ymax =
                        maxalpha, ymin = minalpha), alpha = 0.2) +
      ggplot2::ggtitle("Lineage-Through-Time Plot") +
      ggplot2::theme(legend.position = "none",
                     aspect.ratio = 3 / 4) +
      ggplot2::xlab("Time") + ggplot2::ylab("Number of lineages") +
      ggtext::geom_richtext(
        data = anno,
        ggplot2::aes(
          x = x,
          y = y,
          label = label,
          angle = angle,
          hjust = hjust,
          vjust = vjust
        ),
        fill = "#E8CB9C"
      )

    if (save_plot == TRUE) {
      save_with_parameters(pars_list, plot_ltt, "ltt","png", 5, 4, "retina")
    } else {
      return(plot_ltt)
    }
  }



#' @name edd_plot_las
#' @title Generating line plot of speciation rates of each lineage
#' @description Function to generate a plot showing the transition of speciation
#' rates of each lineage
#' @param raw_data a list of results generated by edd simulation function
#' @param rep_id specify the id of replication to plot
#' @param save_plot Logical, whether save to file or return a ggplot object
#' @return an ggplot object
#' @author Tianjian Qin
#' @keywords phylogenetics
#' @export edd_plot_las
#' @importFrom magrittr %>%
#' @import patchwork
edd_plot_las <- function(raw_data = NULL, rep_id = 1, save_plot = FALSE){
  pars_list <- extract_parameters(raw_data)

  las_table <- cbind(Time = raw_data$ltt[[rep_id]]$time, raw_data$las[[rep_id]])
  las_long <-
    las_table %>% tidyr::gather("Tip", "Lambda", -Time) %>% na.omit()
  las_long <- las_long %>% dplyr::group_by(Time) %>%
    dplyr::mutate(Deviation = Lambda - mean(Lambda))

  anno <- create_annotation(pars_list, y = c(-Inf, -Inf), vjust = c(-1, 0))

  plot_las1 <- ggplot2::ggplot(las_long) +
    ggplot2::geom_path(ggplot2::aes(Time, Lambda, group = Tip, color = Lambda)) +
    viridis::scale_color_viridis(option = "D") +
    ggtext::geom_richtext(
      data = anno,
      ggplot2::aes(
        x = x,
        y = y,
        label = label,
        angle = angle,
        hjust = hjust,
        vjust = vjust
      ),
      fill = "#E8CB9C"
    ) +
    ggplot2::theme(legend.position = "none",
                   aspect.ratio = 1 / 1)

  plot_las2 <- ggplot2::ggplot(las_long) +
    ggplot2::geom_path(ggplot2::aes(Time, Deviation, group = Tip, color = Lambda)) +
    viridis::scale_color_viridis(option = "D") +
    ggplot2::geom_hline(yintercept = 0,
                        linetype = "twodash",
                        color = "grey") +
    ggplot2::theme(legend.position = "right",
                   aspect.ratio = 1 / 1)

  plot_las <- plot_las1 + plot_las2

  if (save_plot == TRUE) {
    save_with_parameters(pars_list =  pars_list,
                         plot = plot_las,
                         which = "las",
                         device = "png",
                         width = 10,
                         height = 8,
                         dpi ="retina")
  } else {
    return(plot_las)
  }
}



#' @name edd_plot_mus
#' @title Generating line plot of extinction rates of each lineage
#' @description Function to generate a plot showing the transition of extinction
#' rates of each lineage
#' @param raw_data a list of results generated by edd simulation function
#' @param rep_id specify the id of replication to plot
#' @param save_plot Logical, whether save to file or return a ggplot object
#' @return an ggplot object
#' @author Tianjian Qin
#' @keywords phylogenetics
#' @export edd_plot_mus
#' @importFrom magrittr %>%
#' @import patchwork
edd_plot_mus <- function(raw_data = NULL, rep_id = 1, save_plot = FALSE){
  pars_list <- extract_parameters(raw_data)

  mus_table <- cbind(Time = raw_data$ltt[[rep_id]]$time, raw_data$mus[[rep_id]])
  mus_long <-
    mus_table %>% tidyr::gather("Tip", "Mu", -Time) %>% na.omit()
  mus_long <- mus_long %>% dplyr::group_by(Time) %>%
    dplyr::mutate(Deviation = Mu - mean(Mu))

  anno <- create_annotation(pars_list, y = c(-Inf, -Inf), vjust = c(-0.8, 0))

  plot_mus1 <- ggplot2::ggplot(mus_long) +
    ggplot2::geom_path(ggplot2::aes(Time, Mu, group = Tip, color = Mu)) +
    viridis::scale_color_viridis(option = "D") +
    ggtext::geom_richtext(
      data = anno,
      ggplot2::aes(
        x = x,
        y = y,
        label = label,
        angle = angle,
        hjust = hjust,
        vjust = vjust
      ),
      fill = "#E8CB9C"
    ) +
    ggplot2::theme(legend.position = "none",
                   aspect.ratio = 1 / 1)

  plot_mus2 <- ggplot2::ggplot(mus_long) +
    ggplot2::geom_path(ggplot2::aes(Time, Deviation, group = Tip, color = Mu)) +
    viridis::scale_color_viridis(option = "D") +
    ggplot2::geom_hline(yintercept = 0,
                        linetype = "twodash",
                        color = "grey") +
    ggplot2::theme(legend.position = "right",
                   aspect.ratio = 1 / 1)

  plot_mus <- plot_mus1 + plot_mus2

  if (save_plot == TRUE) {
    save_with_parameters(pars_list, plot_mus, "mus", "png", 10, 8, "retina")
  } else {
    return(plot_mus)
  }
}



#' @name edd_plot_eds
#' @title Generating line plot of evolutionary distinctiveness of each lineage
#' @description Function to generate a plot showing the transition of evolutionary
#' distinctiveness of each lineage
#' @param raw_data a list of results generated by edd simulation function
#' @param rep_id specify the id of replication to plot
#' @param save_plot Logical, whether save to file or return a ggplot object
#' @return an ggplot object
#' @author Tianjian Qin
#' @keywords phylogenetics
#' @export edd_plot_eds
#' @importFrom magrittr %>%
#' @import patchwork
edd_plot_eds <- function(raw_data = NULL, rep_id = 1, save_plot = FALSE){
  pars_list <- extract_parameters(raw_data)

  eds_table <- cbind(Time = raw_data$ltt[[rep_id]]$time, raw_data$eds[[rep_id]])
  eds_long <-
    eds_table %>% tidyr::gather("Tip", "ED", -Time) %>% na.omit()
  eds_long <- eds_long %>% dplyr::group_by(Time) %>%
    dplyr::mutate(Deviation = ED - mean(ED))

  anno <- create_annotation(pars_list, y = c(Inf, Inf), vjust = c(1, 2.1))

  plot_eds1 <- ggplot2::ggplot(eds_long) +
    ggplot2::geom_path(ggplot2::aes(Time, ED, group = Tip, color = ED)) +
    viridis::scale_color_viridis(option = "D") +
    ggtext::geom_richtext(
      data = anno,
      ggplot2::aes(
        x = x,
        y = y,
        label = label,
        angle = angle,
        hjust = hjust,
        vjust = vjust
      ),
      fill = "#E8CB9C"
    ) +
    ggplot2::theme(legend.position = "none",
                   aspect.ratio = 1 / 1)

  plot_eds2 <- ggplot2::ggplot(eds_long) +
    ggplot2::geom_path(ggplot2::aes(Time, Deviation, group = Tip, color = ED)) +
    viridis::scale_color_viridis(option = "D") +
    ggplot2::geom_hline(yintercept = 0,
                        linetype = "twodash",
                        color = "grey") +
    ggplot2::theme(legend.position = "right",
                   aspect.ratio = 1 / 1)

  plot_eds <- plot_eds1 + plot_eds2

  if (save_plot == TRUE) {
    save_with_parameters(pars_list, plot_eds, "eds", "png", 10, 8, "retina")
  } else {
    return(plot_eds)
  }
}



#' @name plot_las
#' @title Generating plot files of speciation rates
#' @description Function to generate plot files showing the transition of
#' speciation rate of each lineage
#' @param raw_data a list of results generated by edd simulation function
#' @author Tianjian Qin
#' @keywords phylogenetics
#' @export plot_las
plot_las <- function(raw_data) {
  lapply(raw_data, function(x) {
    edd_plot_las(x, save_plot = TRUE)
  })
}


#' @name plot_mus
#' @title Generating plot files of extinction rates
#' @description Function to generate plot files showing the transition of
#' extinction rate of each lineage
#' @param raw_data a list of results generated by edd simulation function
#' @author Tianjian Qin
#' @keywords phylogenetics
#' @export plot_mus
plot_mus <- function(raw_data) {
  lapply(raw_data, function(x) {
    edd_plot_mus(x, save_plot = TRUE)
  })
}



#' @name plot_eds
#' @title Generating plot files of evolutionary distinctiveness-es
#' @description Function to generate plot files showing the transition of
#' evolutionary distinctiveness of each lineage
#' @param raw_data a list of results generated by edd simulation function
#' @author Tianjian Qin
#' @keywords phylogenetics
#' @export plot_eds
plot_eds <- function(raw_data) {
  lapply(raw_data, function(x) {
    edd_plot_eds(x, save_plot = TRUE)
  })
}



#' @name plot_ltt
#' @title Generating plot files of lineages-through-time with confidence interval
#' @description Function to generate plot files showing the lineages-through-time
#' curves with confidence intervals
#' @param raw_data a list of results generated by edd simulation function
#' @author Tianjian Qin
#' @keywords phylogenetics
#' @export plot_ltt
plot_ltt <- function(raw_data) {
  lapply(raw_data, function(x) {
    edd_plot_ltt(x, save_plot = TRUE)
  })
}

