#' @name edd_plot
#' @title Generating plots for a replicated edd simulation
#' @description Function to automatically generate several plots from raw data
#' of a replicated edd simulation
#' @param raw_data a list of results generated by edd simulation function
#' @param which Which part of data to be plotted
#' @param save_plot Logical, decides whether to save the plots to files
#' @param strategy Determine if the simulation is sequential or multi-sessioned
#' or multi-cored
#' @param workers Determine how many sessions are participated in the simulation
#' @param verbose Logical, decides whether to print loading details
#' @return a plot pack containing several plots
#' @author Tianjian Qin
#' @keywords phylogenetics
#' @export edd_plot
edd_plot <- function(raw_data = NULL,
                     which = "all",
                     save_plot = FALSE,
                     strategy = "sequential",
                     workers = 1,
                     verbose = TRUE) {
  check_parallel_arguments(strategy, workers, verbose)
  check_raw_data(raw_data)

  # plot normalized lineages through time
  if (which == "all" | which == "nltt") {
    plot_nltt <- lapply(raw_data, edd_plot_nltt, save_plot = save_plot)
  }

  # plot lineages through time
  if (which == "all" | which == "ltt") {
    plot_ltt <- lapply(raw_data, edd_plot_ltt, save_plot = save_plot)
  }

  # plot speciation rates
  if (which == "all" | which == "las") {
    plot_las <- lapply(raw_data, edd_plot_las, save_plot = save_plot)
  }

  # plot extinction rates
  if (which == "all" | which == "mus") {
    plot_mus <- lapply(raw_data, edd_plot_mus, save_plot = save_plot)
  }

  # plot evolutionary distinctiveness-es
  if (which == "all" | which == "eds") {
    plot_eds <- lapply(raw_data, edd_plot_eds, save_plot = save_plot)
  }
}

#' @name edd_plot_nltt
#' @title Generating nLTT plot for a replicated edd simulation
#' @description Function to generate normalized lineages through time plot from
#' raw data of a replicated edd simulation
#' @param raw_data a list of results generated by edd simulation function
#' @param drop_extinct Logical, decides whether to drop extinct lineages
#' @param save_plot Logical, decides whether to save the plots to files
#' @return an plot object
#' @author Tianjian Qin
#' @keywords phylogenetics
#' @export edd_plot_nltt
edd_plot_nltt <- function(raw_data = NULL,
                          drop_extinct = TRUE,
                          save_plot = FALSE
) {
  if (drop_extinct == TRUE) {
    message("Drawing nLTT plot with trees of extant species")
    df <- nLTT::get_nltt_values(raw_data$tes, dt = 0.01)
  } else {
    message("Drawing nLTT plot with trees of all species")
    df <- nLTT::get_nltt_values(raw_data$tas, dt = 0.01)
  }

  pars_list <- extract_parameters(raw_data)
  anno <- create_annotation(pars_list, vjust = c(1, 2.1))

  plot_nltt <-
    ggplot2::ggplot() +
      ggplot2::geom_point(data = df,
                          ggplot2::aes(t, nltt, color = id),
                          size = I(0.1)) +
      ggplot2::stat_summary(data = df,
                            ggplot2::aes(t, nltt),
                            fun.data = ggplot2::mean_cl_boot,
                            geom = "smooth") +
      ggplot2::ggtitle("Average nLTT plot of phylogenies") +
      ggplot2::labs(x = "Normalized time", y = "Normalized number of lineages") +
      #scale_colour_ggthemr_d() +
      ggtext::geom_richtext(
        data = anno,
        ggplot2::aes(
          x,
          y,
          label = label,
          angle = angle,
          hjust = hjust,
          vjust = vjust
        ),
        fill = "#E8CB9C"
      ) +
      viridis::scale_colour_viridis(discrete = TRUE, option = "A") +
      ggplot2::xlim(0, 1) +
      ggplot2::ylim(0, 1) +
      ggplot2::theme(legend.position = "none",
                     aspect.ratio = 3 / 4)

  if (save_plot == TRUE) {
    save_with_parameters(pars_list, plot_nltt, "nltt", "png", 5, 4, "retina")
  } else {
    return(plot_nltt)
  }
}


#' @name edd_plot_ltt
#' @title Generating LTT plot for a replicated edd simulation
#' @description Function to generate lineages through time plot from
#' raw data of a replicated edd simulation
#' @param raw_data a list of results generated by edd simulation function
#' @param alpha Resolution of the confidence interval
#' @param save_plot true or false, to decide whether to save the plots to files
#' @return an plot object
#' @author Tianjian Qin
#' @keywords phylogenetics
#' @export edd_plot_ltt
edd_plot_ltt <-
  function(raw_data = NULL,
           alpha = 0.05,
           save_plot = FALSE
  ) {
    pars_list <- extract_parameters(raw_data)

    brts <- lapply(raw_data$l_tables, function(x) {
      x[-1, 1]
    })

    ts <- unlist(brts)
    ts <- unique(ts)
    ts <- sort(ts)

    df <- calculate_CI(brts, ts, alpha = alpha)
    colnames(df) <- c("t", "median", "minalpha", "maxalpha", "mean")
    df <- as.data.frame(df)

    anno <- create_annotation(pars_list, vjust = c(1, 2.1))

    plot_ltt <-
      ggplot2::ggplot(df) +
        ggplot2::geom_line(ggplot2::aes(t, mean)) +
        ggplot2::geom_ribbon(ggplot2::aes(t, mean, ymax =
          maxalpha, ymin = minalpha), alpha = 0.2) +
        ggplot2::ggtitle("Lineage-Through-Time Plot") +
        ggplot2::theme(legend.position = "none",
                       aspect.ratio = 3 / 4) +
        ggplot2::xlab("Time") +
        ggplot2::ylab("Number of lineages") +
        ggtext::geom_richtext(
          data = anno,
          ggplot2::aes(
            x = x,
            y = y,
            label = label,
            angle = angle,
            hjust = hjust,
            vjust = vjust
          ),
          fill = "#E8CB9C"
        )

    if (save_plot == TRUE) {
      save_with_parameters(pars_list, plot_ltt, "ltt", "png", 5, 4, "retina")
    } else {
      return(plot_ltt)
    }
  }


#' @name edd_plot_las
#' @title Generating line plot of speciation rates of each lineage
#' @description Function to generate a plot showing the transition of speciation
#' rates of each lineage
#' @param raw_data a list of results generated by edd simulation function
#' @param rep_id specify the id of replication to plot
#' @param save_plot Logical, whether save to file or return a ggplot object
#' @return an ggplot object
#' @author Tianjian Qin
#' @keywords phylogenetics
#' @export edd_plot_las
#' @importFrom magrittr %>%
#' @import patchwork
edd_plot_las <- function(raw_data = NULL, rep_id = 1, save_plot = FALSE) {
  pars_list <- extract_parameters(raw_data)

  las_table <- cbind(Time = raw_data$ltt[[rep_id]]$time, raw_data$las[[rep_id]])
  las_long <-
    las_table %>%
      tidyr::gather("Tip", "Lambda", -Time) %>%
      na.omit()
  las_long <- las_long %>%
    dplyr::group_by(Time) %>%
    dplyr::mutate(Deviation = Lambda - mean(Lambda))

  anno <- create_annotation(pars_list, y = c(-Inf, -Inf), vjust = c(-1, 0))

  plot_las1 <- ggplot2::ggplot(las_long) +
    ggplot2::geom_path(ggplot2::aes(Time, Lambda, group = Tip, color = Lambda)) +
    viridis::scale_color_viridis(option = "D") +
    ggtext::geom_richtext(
      data = anno,
      ggplot2::aes(
        x = x,
        y = y,
        label = label,
        angle = angle,
        hjust = hjust,
        vjust = vjust
      ),
      fill = "#E8CB9C"
    ) +
    ggplot2::theme(legend.position = "none",
                   aspect.ratio = 1 / 1)

  plot_las2 <- ggplot2::ggplot(las_long) +
    ggplot2::geom_path(ggplot2::aes(Time, Deviation, group = Tip, color = Lambda)) +
    viridis::scale_color_viridis(option = "D") +
    ggplot2::geom_hline(yintercept = 0,
                        linetype = "twodash",
                        color = "grey") +
    ggplot2::theme(legend.position = "right",
                   aspect.ratio = 1 / 1)

  plot_las <- plot_las1 + plot_las2

  if (save_plot == TRUE) {
    save_with_parameters(pars_list = pars_list,
                         plot = plot_las,
                         which = "las",
                         device = "png",
                         width = 10,
                         height = 8,
                         dpi = "retina")
  } else {
    return(plot_las)
  }
}


#' @name edd_plot_mus
#' @title Generating line plot of extinction rates of each lineage
#' @description Function to generate a plot showing the transition of extinction
#' rates of each lineage
#' @param raw_data a list of results generated by edd simulation function
#' @param rep_id specify the id of replication to plot
#' @param save_plot Logical, whether save to file or return a ggplot object
#' @return an ggplot object
#' @author Tianjian Qin
#' @keywords phylogenetics
#' @export edd_plot_mus
#' @importFrom magrittr %>%
#' @import patchwork
edd_plot_mus <- function(raw_data = NULL, rep_id = 1, save_plot = FALSE) {
  pars_list <- extract_parameters(raw_data)

  mus_table <- cbind(Time = raw_data$ltt[[rep_id]]$time, raw_data$mus[[rep_id]])
  mus_long <-
    mus_table %>%
      tidyr::gather("Tip", "Mu", -Time) %>%
      na.omit()
  mus_long <- mus_long %>%
    dplyr::group_by(Time) %>%
    dplyr::mutate(Deviation = Mu - mean(Mu))

  anno <- create_annotation(pars_list, y = c(-Inf, -Inf), vjust = c(-0.8, 0))

  plot_mus1 <- ggplot2::ggplot(mus_long) +
    ggplot2::geom_path(ggplot2::aes(Time, Mu, group = Tip, color = Mu)) +
    viridis::scale_color_viridis(option = "D") +
    ggtext::geom_richtext(
      data = anno,
      ggplot2::aes(
        x = x,
        y = y,
        label = label,
        angle = angle,
        hjust = hjust,
        vjust = vjust
      ),
      fill = "#E8CB9C"
    ) +
    ggplot2::theme(legend.position = "none",
                   aspect.ratio = 1 / 1)

  plot_mus2 <- ggplot2::ggplot(mus_long) +
    ggplot2::geom_path(ggplot2::aes(Time, Deviation, group = Tip, color = Mu)) +
    viridis::scale_color_viridis(option = "D") +
    ggplot2::geom_hline(yintercept = 0,
                        linetype = "twodash",
                        color = "grey") +
    ggplot2::theme(legend.position = "right",
                   aspect.ratio = 1 / 1)

  plot_mus <- plot_mus1 + plot_mus2

  if (save_plot == TRUE) {
    save_with_parameters(pars_list, plot_mus, "mus", "png", 10, 8, "retina")
  } else {
    return(plot_mus)
  }
}


#' @name edd_plot_eds
#' @title Generating line plot of evolutionary distinctiveness of each lineage
#' @description Function to generate a plot showing the transition of evolutionary
#' distinctiveness of each lineage
#' @param raw_data a list of results generated by edd simulation function
#' @param rep_id specify the id of replication to plot
#' @param save_plot Logical, whether save to file or return a ggplot object
#' @return an ggplot object
#' @author Tianjian Qin
#' @keywords phylogenetics
#' @export edd_plot_eds
#' @importFrom magrittr %>%
#' @import patchwork
edd_plot_eds <- function(raw_data = NULL, rep_id = 1, save_plot = FALSE) {
  pars_list <- extract_parameters(raw_data)

  eds_table <- cbind(Time = raw_data$ltt[[rep_id]]$time, raw_data$eds[[rep_id]])
  eds_long <-
    eds_table %>%
      tidyr::gather("Tip", "ED", -Time) %>%
      na.omit()
  eds_long <- eds_long %>%
    dplyr::group_by(Time) %>%
    dplyr::mutate(Deviation = ED - mean(ED))

  anno <- create_annotation(pars_list, y = c(Inf, Inf), vjust = c(1, 2.1))

  plot_eds1 <- ggplot2::ggplot(eds_long) +
    ggplot2::geom_path(ggplot2::aes(Time, ED, group = Tip, color = ED)) +
    viridis::scale_color_viridis(option = "D") +
    ggtext::geom_richtext(
      data = anno,
      ggplot2::aes(
        x = x,
        y = y,
        label = label,
        angle = angle,
        hjust = hjust,
        vjust = vjust
      ),
      fill = "#E8CB9C"
    ) +
    ggplot2::theme(legend.position = "none",
                   aspect.ratio = 1 / 1)

  plot_eds2 <- ggplot2::ggplot(eds_long) +
    ggplot2::geom_path(ggplot2::aes(Time, Deviation, group = Tip, color = ED)) +
    viridis::scale_color_viridis(option = "D") +
    ggplot2::geom_hline(yintercept = 0,
                        linetype = "twodash",
                        color = "grey") +
    ggplot2::theme(legend.position = "right",
                   aspect.ratio = 1 / 1)

  plot_eds <- plot_eds1 + plot_eds2

  if (save_plot == TRUE) {
    save_with_parameters(pars_list, plot_eds, "eds", "png", 10, 8, "retina")
  } else {
    return(plot_eds)
  }
}


edd_plot_balance <- function(stat_pack = NULL) {
  plot_data <- dplyr::filter(stat_tree_balance_long,
                             lambda == 0.5 &
                               mu == 0.2 &
                               metric == "pd")

  blum_plot <- ggplot2::ggplot(dplyr::filter(plot_data, balance == "blum")) +
    ggplot2::geom_boxplot(ggplot2::aes(beta_phi, value, fill = beta_n)) +
    ggplot2::facet_wrap(. ~ offset2, nrow = 1) +
    ggplot2::scale_y_continuous(trans = "sqrt") +
    ggplot2::ylab("Blum") +
    ggplot2::theme(axis.title.x = ggplot2::element_blank(),
                   axis.text.x = ggplot2::element_blank(),
                   axis.ticks.x = ggplot2::element_blank(),
                   axis.line.x = ggplot2::element_blank())

  colless_plot <- ggplot2::ggplot(dplyr::filter(plot_data, balance == "colless")) +
    ggplot2::geom_boxplot(ggplot2::aes(beta_phi, value, fill = beta_n)) +
    ggplot2::facet_wrap(. ~ offset2, nrow = 1) +
    ggplot2::scale_y_continuous(trans = "sqrt") +
    ggplot2::ylab("Colless") +
    ggplot2::theme(axis.title.x = ggplot2::element_blank(),
                   axis.text.x = ggplot2::element_blank(),
                   axis.ticks.x = ggplot2::element_blank(),
                   strip.background = ggplot2::element_blank(),
                   strip.text.x = ggplot2::element_blank(),
                   axis.line.x = ggplot2::element_blank())

  sackin_plot <- ggplot2::ggplot(dplyr::filter(plot_data, balance == "sackin")) +
    ggplot2::geom_boxplot(ggplot2::aes(beta_phi, value, fill = beta_n)) +
    ggplot2::facet_wrap(. ~ offset2, nrow = 1) +
    ggplot2::scale_y_continuous(trans = "sqrt") +
    ggplot2::scale_x_discrete(labels = c("-0.05", "-0.01", "0", "0.0005", "0.001")) +
    ggplot2::ylab("Sackin") +
    ggplot2::xlab(expression(beta[italic(Phi)])) +
    ggplot2::theme(strip.background = ggplot2::element_blank(),
                   strip.text.x = ggplot2::element_blank())

  # Tree Balance indices by Beta_Phi, . ~ Offset, grouped by Beta_N
  blum_plot +
    ggplot2::ggtitle(expression("Tree Balance indices of PD, comparisions between offset methods, " ~ lambda ~ "=" ~ "0.5," ~ mu ~ "=" ~ "0.2")) +
    colless_plot +
    sackin_plot +
    patchwork::plot_layout(ncol = 1, guides = "collect") &
    ggplot2::labs(fill = expression(beta[italic(N)]))

  ggplot2::ggsave("result/plot/tree_balance_pd_0.5_0.2.png", dpi = "retina")

  plot_data_pd <- dplyr::filter(stat_tree_balance_long,
                                lambda == 0.5 &
                                  mu == 0 &
                                  metric == "pd" &
                                  offset == "simtime")

  plot_data_ed <- dplyr::filter(stat_tree_balance_long,
                                lambda == 0.5 &
                                  mu == 0 &
                                  metric == "ed")

  pd_plot <- ggplot2::ggplot(plot_data_pd) +
    ggplot2::geom_boxplot(ggplot2::aes(beta_phi, value, fill = beta_n)) +
    ggplot2::facet_wrap(. ~ balance, nrow = 1, scales = "free_y") +
    #ggplot2::scale_y_continuous(trans = "sqrt") +
    ggplot2::ylab("PD") +
    ggplot2::theme(axis.title.x = ggplot2::element_blank(),
                   axis.text.x = ggplot2::element_blank(),
                   axis.ticks.x = ggplot2::element_blank(),
                   axis.line.x = ggplot2::element_blank())
  ed_plot <- ggplot2::ggplot(plot_data_ed) +
    ggplot2::geom_boxplot(ggplot2::aes(beta_phi, value, fill = beta_n)) +
    ggplot2::facet_wrap(. ~ balance, nrow = 1, scales = "free_y") +
    ggplot2::scale_x_discrete(labels = c("-0.05", "-0.01", "0", "0.0005", "0.001")) +
    #ggplot2::scale_y_continuous(trans = "sqrt") +
    ggplot2::ylab("ED") +
    ggplot2::xlab(expression(beta[italic(Phi)])) +
    ggplot2::theme(strip.background = ggplot2::element_blank(),
                   strip.text.x = ggplot2::element_blank())

  pd_plot +
    ggplot2::ggtitle(expression("Tree Balance indices, comparisons between PD (offset by simtime) and ED, " ~ lambda ~ "=" ~ "0.5," ~ mu ~ "=" ~ "0.2")) +
    ed_plot +
    patchwork::plot_layout(nrow = 2, guides = "collect") &
    ggplot2::labs(fill = expression(beta[italic(N)]))

  ggplot2::ggsave("result/plot/tree_balance_ed_pd_0.5_0.2.png", dpi = "retina")

}