#' @name extract_edd_result
#' @title Extracting a specified component of the result list generated in
#' simulation
#' @description Function to extract a specified component of the result list
#' generated in edd simulation
#' @param result A list of result generated by edd simulation function
#' @param nrep The number of replication used in the simulation
#' @param which Specifying which part of the result to be extracted
#' @param nlist The number of components in generated list of result
#' @return A list of extracted results
#' @author Tianjian Qin
#' @keywords phylogenetics
#' @export extract_edd_result
extract_edd_result <- function(result, nrep, which, nlist = 8) {
  out <-
    return(result[seq(which, nlist * nrep, by = nlist)])
}



#' @name bind_raw
#' @title Binding extracted results in simulation
#' @description Function to bind all results extracted from replicated edd
#' simulation
#' @param raw_data a list of results generated by edd simulation function
#' @param nrep the number of replications
#' @return A binded list of the results
#' @author Tianjian Qin
#' @keywords phylogenetics
#' @export bind_raw
bind_raw <- function(raw_data = NULL, nrep = NULL) {
  if (nrep == 1) stop("Simulation is not replicated")
  binded_data <- lapply(raw_data, as.data.frame)

  for (i in 1:nrep) {
    binded_data[[i]]["nrep"] <- rep(i, times = nrow(binded_data[[i]]))
  }

  return(binded_data)
}


#' @name match_raw
#' @title Matching lineages and values in raw data
#' @description Function to match lineages names and corresponding values from
#' replicated edd simulation
#' @param x a list of values to be matched with lineages
#' @param y the lineage lists of the replicated edd simulation
#' @return A matched list with values and corresponding lineages
#' @author Tianjian Qin
#' @keywords phylogenetics
#' @export match_raw
match_raw <- function(x = NULL, y = NULL){
 purrr:::modify2(x, y, ~if(is_list(.x)) fun(.x, .y)
                  else purrr::set_names(.x, paste0('t', abs(.y))))
}



#' @name edd_sim_rep
#' @title Running a replicated edd simulation
#' @description Function to automatically run a replicated edd simulation
#' @param nrep the number of replication
#' @param pars parameters used in a edd simulation
#' @param age the total running time of a edd simulation
#' @param model the type of model used in a edd simulation
#' @param metric the metric used in a edd simulation
#' @param offset the offset method for Phi used in a edd simulation
#' @return a list of simulation results
#' @author Tianjian Qin
#' @keywords phylogenetics
#' @export edd_sim_rep
edd_sim_rep <-
  function(nrep = 5,
           pars = c(0.5, 0.1, -0.001, -0.001, 0, 001, 0, 001),
           age = 5,
           model = "dsde2",
           metric = "ed",
           offset = "none") {
    if (nrep < 2)
      stop("Must have more than 1 replicates")

    # do replicated simulations
    raw_data <- replicate(nrep, {
      DDD::edd_sim(pars,
                   age,
                   model,
                   metric,
                   offset)
    })

    # store all initial parameters
    all_pars <- list(
      nrep = nrep,
      pars = pars,
      age = age,
      model = model,
      metric = metric,
      offset = offset
    )

    # combine data
    out <- list(
      all_pars = all_pars,
      tes = raw_data[1,],
      tas = raw_data[2,],
      l_tables = raw_data[3,],
      brts = raw_data[4,],
      nltt = raw_data[5,],
      eds = raw_data[6,],
      las  = raw_data[7,],
      mus  = raw_data[8,],
      linlists = raw_data[9,]
    )

    return(out)
  }

#' @name edd_wrapper
#' @title Conducting a edd simulation and plotting the results
#' @description Function to automatically run a replicated edd simulation and then
#' produce several plots from the results
#' @param nrep the number of replication
#' @param pars parameters used in a edd simulation
#' @param age the total running time of a edd simulation
#' @param model the type of model used in a edd simulation
#' @param metric the metric used in a edd simulation
#' @param offset the offset method for Phi used in a edd simulation
#' @param ... other parameters passed to plot or stat functions
#' @author Tianjian Qin
#' @keywords phylogenetics
#' @export edd_wrapper
edd_wrapper <-
  function(input = NULL,
           plot_opt = NULL,
           stat_opt = NULL,
           ...) {
    raw_data <-
      edd_sim_rep(input$nrep,
                  input$pars,
                  input$age,
                  input$model,
                  input$metric,
                  input$offset)

    plot_pack <- edd_plot(raw_data, stat_opt, ...)
    stat_pack <- edd_stat(raw_data, plot_opt, ...)

    return(raw_data, plot_pack, stat_pack)
  }



edd_sim_combo <- function(combo, plot_opt, stat_opt) {
  purrr::map(combo, edd_wrapper, plot_opt, stat_opt)
}



edd_combo_maker <-
  function(pars_combo,
           nrep_combo,
           age_combo,
           model_combo,
           metric_combo,
           offset_combo) {

    return(combo)
  }
