#' @name pdd_simulation_plot
#' @title Plotting results of a replicated pdd simulation
#' @description Function to automatically produce several plots from the results
#' of a replicated pdd simulation
#' @param result a list of extracted results
#' @param pars the parameters used in simulation being plotted
#' @param age the total simulation time
#' @param model the model used in the simulation
#' @param offset the offset method for Phi used in a pdd simulation
#' @return a plot grid generated by cow_plot
#' @author Tianjian Qin
#' @keywords phylogenetics
#' @export pdd_simulation_plot
pdd_simulation_plot <- function(result, pars, age, model, offset) {
  plotN <-
    ggplot2::ggplot(result[[2]], aes(time, N, group = rep, color = rep)) + ggplot2::geom_line() +
    ggplot2::theme(legend.position = "none") + xlab("age")

  if (model == "dsce1" | model == "dsde1") {
    plotPhi <-
      ggplot2::ggplot(result[[2]], aes(time, Phi, group = rep, color = rep)) + ggplot2::geom_line() +
      ggplot2::theme(legend.position = "none") + xlab("age") + ggplot2::geom_hline(yintercept = pars[3])
    title <-
      cowplot::ggdraw() + cowplot::draw_label(
        paste(
          model,
          ", ",
          "lambda = ",
          pars[1],
          ", ",
          "mu = ",
          pars[2],
          ", ",
          "K = ",
          pars[3],
          ", ",
          "age = ",
          age,
          ", ",
          "offset = ",
          offset
        ),
        fontface = 'bold'
      )
  } else if (model == "dsde2") {
    plotPhi <-
      ggplot2::ggplot(result[[2]], aes(time, Phi, group = rep, color = rep)) + ggplot2::geom_line() +
      ggplot2::theme(legend.position = "none") + xlab("age")
    title <-
      cowplot::ggdraw() + cowplot::draw_label(
        paste(
          model,
          ", ",
          "lambda = ",
          pars[1],
          ", ",
          "mu = ",
          pars[2],
          ", ",
          "betaN = ",
          pars[3],
          ", ",
          "betaPhi = ",
          pars[4],
          ", ",
          "gammaN = ",
          pars[5],
          ", ",
          "gammaPhi = ",
          pars[6],
          ", ",
          "age = ",
          age,
          ", ",
          "offset = ",
          offset
        ),
        fontface = 'bold'
      )
  } else if (model == "dsce2") {
    plotPhi <-
      ggplot2::ggplot(result[[2]], aes(time, Phi, group = rep, color = rep)) + ggplot2::geom_line() +
      ggplot2::theme(legend.position = "none") + xlab("age")
    title <-
      cowplot::ggdraw() + cowplot::draw_label(
        paste(
          model,
          ", ",
          "lambda = ",
          pars[1],
          ", ",
          "mu = ",
          pars[2],
          ", ",
          "betaN = ",
          pars[3],
          ", ",
          "betaPhi = ",
          pars[4],
          ", ",
          "age = ",
          age,
          ", ",
          "offset = ",
          offset
        ),
        fontface = 'bold'
      )
  }

  plotla <-
    ggplot2::ggplot(result[[2]], aes(time, lambda, group = rep, color = rep)) + ggplot2::geom_line() +
    ggplot2::theme(legend.position = "none") + xlab("age")
  plotmu <-
    ggplot2::ggplot(result[[2]], aes(time, mu, group = rep, color = rep)) + ggplot2::geom_line() +
    ggplot2::theme(legend.position = "none") + xlab("age")
  plotall <- cowplot::plot_grid(plotN, plotPhi, plotla, plotmu)

  plotwithtitle <-
    cowplot::plot_grid(title,
                       plotall,
                       ncol = 1,
                       rel_heights = c(0.1, 1))

  return(plotwithtitle)
}

#' @name edd_simulation_plot
#' @title Plotting results of a replicated edd simulation
#' @description Function to automatically produce several plots from the results
#' of a replicated edd simulation
#' @param result a list of extracted results
#' @param pars the parameters used in simulation being plotted
#' @param age the total simulation time
#' @param model the model used in the simulation
#' @return a plot grid generated by cow_plot
#' @author Tianjian Qin
#' @keywords phylogenetics
#' @export edd_simulation_plot
edd_simulation_plot <-
  function(result,
           pars,
           age,
           model,
           offset) {
    plotN <-
      ggplot2::ggplot(result[[2]], aes(time, N, group = rep, color = rep)) + ggplot2::geom_line() +
      ggplot2::theme(legend.position = "none") + xlab("age")

    tree <-
      ggtree::ggtree(result$result_raw[, 1]$tas) + ggtree::geom_tiplab(size = 4)

    relas <-
      dplyr::bind_cols(result$result_raw[, 1]$LTT$time, result$result_raw[, 1]$las)
    relas <- relas %>% tibble::column_to_rownames(var = "...1")

    remus <-
      dplyr::bind_cols(result$result_raw[, 1]$LTT$time, result$result_raw[, 1]$mus)
    remus <- remus %>% tibble::column_to_rownames(var = "...1")

    plotlas <- ggtree::gheatmap(
      tree,
      t(relas),
      offset = 0.6,
      width = 0.8,
      colnames = FALSE,
      legend_title = "PSR"
    )

    plotmus <- ggtree::gheatmap(
      tree,
      t(remus),
      offset = 0.6,
      width = 0.8,
      colnames = FALSE,
      legend_title = "PER"
    )

    plot_bottom <- cowplot::plot_grid(plotlas, plotmus)

    plotall <-
      cowplot::plot_grid(plotN, plot_bottom, nrow = 2, rel_heights = c(1, 2))

    return(plotall)
  }
