#' @name extract_edd_result
#' @title Extracting a specified component of the result list generated in
#' simulation
#' @description Function to extract a specified component of the result list
#' generated in edd simulation
#' @param result A list of result generated by edd simulation function
#' @param rep The number of replication used in the simulation
#' @param which Specifying which part of the result to be extracted
#' @param nlist The number of components in generated list of result
#' @return A list of extracted results
#' @author Tianjian Qin
#' @keywords phylogenetics
#' @export extract_edd_result
extract_edd_result <- function(result, rep, which, nlist = 8) {
  out <-
    return(result[seq(which, nlist * rep, by = nlist)])
}



#' @name bind_result
#' @title Binding extracted results in simulation
#' @description Function to bind all results extracted from edd simulation
#' @param result a list generated by edd simulation function
#' @return A binded list of extracted results
#' @author Tianjian Qin
#' @keywords phylogenetics
#' @export bind_result
bind_result <- function(result) {
  out <- lapply(result, as.data.frame)
  n <- length(out)

  for (i in 1:n) {
    out[[i]]["rep"] <- rep(i, times = nrow(out[[i]]))
  }

  return(dplyr::bind_rows(out))
}



#' @name edd_simulation_replicated
#' @title Running a replicated edd simulation
#' @description Function to automatically run a replicated edd simulation
#' @param rep the number of replication
#' @param pars parameters used in a edd simulation
#' @param age the total running time of a edd simulation
#' @param model the type of model used in a edd simulation
#' @param metric the metric used in a edd simulation
#' @param offset the offset method for Phi used in a edd simulation
#' @return a list of simulation results
#' @author Tianjian Qin
#' @keywords phylogenetics
#' @export edd_simulation_replicated
edd_simulation_replicated <-
  function(rep, pars, age, model, metric, offset) {

    result_pars <- extract_edd_result(results, rep, 5)
    result_pars_binded <- bind_result(result_pars)

    return(list(result_pars = result_pars, result_pars_binded = result_pars_binded))
  }



#' @name edd_simulation_wrapper
#' @title Conducting a edd simulation and plotting the results
#' @description Function to automatically run a replicated edd simulation and then
#' produce several plots from the results
#' @param rep the number of replication
#' @param pars parameters used in a edd simulation
#' @param age the total running time of a edd simulation
#' @param model the type of model used in a edd simulation
#' @param metric the metric used in a edd simulation
#' @param offset the offset method for Phi used in a edd simulation
#' @author Tianjian Qin
#' @keywords phylogenetics
#' @export edd_simulation_wrapper
edd_simulation_wrapper <- function(rep, pars, age, model, metric, offset) {
  # do replicated simulations
  results <- replicate(rep, {
    DDD::edd_sim(pars,
                 age,
                 model,
                 metric,
                 offset)
  })

  # extract and reshape results

  if (model == "dsce1" | model == "dsde1") {
    if (is.null(pars[3])) {
      stop("missing K")
    }
  }

  plot_pack <- edd_simulation_plot(result, pars, age, model, offset)

  input_output_pack <-
    list(
      result = result,
      pars = pars,
      age = age,
      model = model,
      metric = metric,
      offset = offset
    )

  return(list(data = input_output_pack, plot = plot_pack))
}
